user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

producto:
    resource: "@ProductoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
